package mechanicraft.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

//Date: 5/2/2013 2:03:30 PM
//Template version 1.1
//Java generated by Techne
//Keep in mind that you still need to fill in some blanks
//- ZeuX
public class ModelAnvilCraft extends ModelBase
{
	//fields
	ModelRenderer Base;
    ModelRenderer Base2;
    ModelRenderer Leg;
    ModelRenderer Main;
    ModelRenderer Extension1;
    ModelRenderer Extension2;
    ModelRenderer Extension3;

    public ModelAnvilCraft()
    {
    	textureWidth = 64;
    	textureHeight = 32;
 
    	Base = new ModelRenderer(this, 0, 0);
    	Base.addBox(0F, 0F, 0F, 8, 2, 8);
    	Base.setRotationPoint(-4F, 22F, -4F);
    	Base.setTextureSize(64, 32);
    	Base.mirror = true;
    	setRotation(Base, 0F, 0F, 0F);
    	Base2 = new ModelRenderer(this, 33, 0);
    	Base2.addBox(0F, 0F, 0F, 6, 1, 6);
    	Base2.setRotationPoint(-3F, 21F, -3F);
    	Base2.setTextureSize(64, 32);
    	Base2.mirror = true;
    	setRotation(Base2, 0F, 0F, 0F);
    	Leg = new ModelRenderer(this, 0, 24);
    	Leg.addBox(0F, 0F, 0F, 3, 4, 3);
    	Leg.setRotationPoint(-1.5F, 17F, -1.5F);
    	Leg.setTextureSize(64, 32);
    	Leg.mirror = true;
    	setRotation(Leg, 0F, 0F, 0F);
    	Main = new ModelRenderer(this, 0, 11);
    	Main.addBox(0F, 0F, 0F, 4, 4, 8);
    	Main.setRotationPoint(-2F, 13F, -3F);
    	Main.setTextureSize(64, 32);
    	Main.mirror = true;
    	setRotation(Main, 0F, 0F, 0F);
    	Extension1 = new ModelRenderer(this, 25, 11);
    	Extension1.addBox(0F, 0F, 0F, 3, 3, 1);
    	Extension1.setRotationPoint(-1.5F, 13.5F, -4F);
    	Extension1.setTextureSize(64, 32);
    	Extension1.mirror = true;
    	setRotation(Extension1, 0F, 0F, 0F);
    	Extension2 = new ModelRenderer(this, 25, 16);
    	Extension2.addBox(0F, 0F, 0F, 2, 2, 2);
    	Extension2.setRotationPoint(-1F, 13.5F, -5.5F);
    	Extension2.setTextureSize(64, 32);
    	Extension2.mirror = true;
    	setRotation(Extension2, 0F, 0F, 0F);
    	Extension3 = new ModelRenderer(this, 25, 21);
    	Extension3.addBox(0F, 0F, 0F, 1, 1, 1);
    	Extension3.setRotationPoint(-0.5F, 13.5F, -6.5F);
    	Extension3.setTextureSize(64, 32);
    	Extension3.mirror = true;
    	setRotation(Extension3, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
    	super.render(entity, f, f1, f2, f3, f4, f5);
    	setRotationAngles(f, f1, f2, f3, f4, f5);
    	Base.render(f5);
    	Base2.render(f5);
    	Leg.render(f5);
    	Main.render(f5);
    	Extension1.render(f5);
    	Extension2.render(f5);
    	Extension3.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
    	model.rotateAngleX = x;
    	model.rotateAngleY = y;
    	model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
    {
    	super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    }

    public void renderAll()
    {
    	Base.render(0.0650F);
    	Base2.render(0.0650F);
    	Leg.render(0.0650F);
    	Main.render(0.0650F);
    	Extension1.render(0.0650F);
    	Extension2.render(0.0650F);
    	Extension3.render(0.0650F);
    }

}